version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: file-rotation-api
    ports:
      - "8080:80"
    volumes:
      - ./data:/var/www/html/data
    environment:
      - APP_ENV=production
    restart: unless-stopped
    networks:
      - file-rotation-network

networks:
  file-rotation-network:
    driver: bridge